# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 空
subtitle: 我要信奉:我学过的每一样东西，我遭受的每一样苦难，都会在我一生中的某个时候派上用场 ——佩内洛普·菲兹杰拉德 《离岸》

description: 看到一片净土，让我远离死亡
author: voidzhang
language: zh-Hans #中文博客
timezone: #网站时区。Hexo 默认使用您电脑的时区。时区列表。比如说：America/New_York, Japan, 和 UTC

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://coffee1993.github.io
root: /
permalink: :year/:month/:day/:title/ #文章的永久链接格式
permalink_defaults:


# Directory #网站目录
source_dir: source #资源文件夹存放内容
public_dir: public #存放生成的站点
tag_dir: tags #标签文件夹
archive_dir: archives #归档文件夹
category_dir: categories #分类文件夹
code_dir: downloads/code #code 文件夹
i18n_dir: :lang #国际化文件夹
skip_render: # 掉过指定的渲染文件 用glob表达式

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
auto_spacing: false #中英文之间加空格
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0 #把文件名称转换成 1 大写 2 小写
render_drafts: false #显示草稿
post_asset_folder: false #启动Asset文件夹
relative_link: false #把链接改为根目录的相对地址
future: true #显示未来的文章
highlight: #代码块位置
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag 分类标签
default_category: uncategorized #默认分类
category_map: #分类别名
tag_map: #标签别名

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10 #每页显示文章数量
pagination_dir: page #分页目录

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
# theme: landscape
theme: next
duoshuo_shortname: void
# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: https://github.com/coffee1993/coffee1993.github.io.git
  branch: master


plugins:
#   - hexo-qiniu-sync
# #七牛云存储设置
# ##offline       是否离线. 离线状态将使用本地地址渲染
# ##sync          是否同步
# ##bucket        空间名称.
# ##access_key    上传密钥AccessKey
# ##secret_key    上传密钥SecretKey
# ##dirPrefix     上传的资源子目录前缀.如设置，需与urlPrefix同步
# ##urlPrefix     外链前缀.
# ##local_dir     本地目录.
# ##update_exist  是否更新已经上传过的文件(仅文件大小不同或在上次上传后进行更新的才会重新上传)
# ##image/js/css  子参数folder为不同静态资源种类的目录名称，一般不需要改动
# ##image.extend  这是个特殊参数，用于生成缩略图或加水印等操作。具体请参考http://developer.qiniu.com/docs/v6/api/reference/fop/image/
# ##              可使用基本图片处理、高级图片处理、图片水印处理这3个接口。例如 ?imageView2/2/w/500 即生成宽度最多500px的缩略图
# qiniu:
#   offline: false
#   sync: true
#   bucket: blogger
#   access_key: 3Lcw4rchfUfNv6L8Zk6-eRBlWRnPTCxDPFndfAw6
#   secret_key: BEhQYtvOG4myAx14XbASlbIlSAb7tK2Cq2aB-MQb
#   dirPrefix: blogger
#   urlPrefix: http://7xrw2w.com1.z0.glb.clouddn.com
#   local_dir: static
#   update_exist: true
#   image:
#     folder: images
#     extend:
#   js:
#     folder: js
#   css:
#     folder: css
